#  password := 123
#    username := shopteam
#    db_name := shop
#    init_dir := $(CURDIR)/storage/init_db
#
#  start_db:
#    (docker stop postgres && docker rm postgres) || true
#    docker run \
#    --name postgres \
#    -e POSTGRESQL_USERNAME=$(username) \
#    -e POSTGRESQL_DATABASE=$(db_name) \
#    -e POSTGRESQL_PASSWORD=$(password) \
#    -p 5432:5432 \
#    -v $(init_dir):/docker-entrypoint-initdb.d \
#    bitnami/postgresql:latest

version: '3.5'

services:
  shop:
    build: .
    image: shop
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    shm_size: "2gb"
    environment:
      PORT: ":8000"
#      SHOP_UID: ${UID:-1000}                   # user id, should match your host user id
#      SHOP_GID: ${GID:-1000}                   # group id

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" # database port (host:container)
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shopteam
      POSTGRES_PASSWORD: 123
    volumes:
      - ./storage/init_db:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2.7
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - postgres

networks:
  default:
    name: shop
    driver: bridge

